name: "Goimports Check Action"
description: "A ready to use GitHub action to check goimports with folder/file exclusions"
author: "Hemanth Krishna (DarthBenro008) hkpdev008@gmail.com"
inputs:
  root-path:
    description: "Root path of GoImports"
    required: true
    default: "./"
  excludes:
    description: "A comma seperated string of directories to exclude"
    required: false
    default: ""
outputs:
  goimports-output:
    description: "The goimports output if the command fail"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.root-path }}

branding:
  icon: "play-circle"
  color: "gray-dark"
